# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSStudyCollection' do
    use_frameworks!


    #OC
    pod 'ReactiveObjC'
    pod 'Masonry', '~> 1.1.0'
    pod 'AFNetworking', '3.2.1'
    
    pod 'Aspects', '~> 1.4.1' #黑魔法库
 
    #Swift
    pod 'ReactiveCocoa'
    pod 'RxSwift'
    pod 'RxCocoa'
end
